### ISSUE TITLE
flaky test AsyncSchedulerSuite

### ISSUE THREAD

**Issue by TapanVaishnav** [monix/monix#1078]
`monix.execution.internal.AsyncSchedulerSuite` is failing frequently these days without any specific reason.

**Comment by alexandru** [comment]
`AsyncSchedulerSuite`, the version for Scala.js / JavaScript, has a test for ... "*scheduleWithFixedRate should compensate for scheduling inaccuracy*".

This fails because on top of under-powered machines, like those on Travis, big delas that are more than 30 millis can happen, as used in the test.

In #1221 I disabled it on top of CI / Travis.
