### ISSUE TITLE
AtomicAny.compareAndSet fails working properly with case class

### ISSUE THREAD

**Issue by fspillner** [monix/monix#1358]
Hi!

While I was playing a bit with `CircuitBreaker` just get the idea what it does and so and it didn't work that way I'd expect. I debugged the code a bit and I found out that the `AtomicAny.compareAndSet` doesn't behave as expected on my machine and it breaks the CircuitBreaker which relies on it.

Monix: 3.3.0

JVM:
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 25.272-b10-jvmci-20.3-b06, mixed mode)

Steps:

```scala
final case class Test(state: Int)

val state = AtomicAny(Test(0))

println("initial state:")
println(state.get())
// Test(0)

println("compareAndSet:")
println {
  state.compareAndSet(Test(0), Test(1))
}
// false

println("After compareAndSet:")
println(state.get())
// Test(0)
```
What can be the problem?

**Comment by paualarco** [comment]
Hello @fspillner, 

The object you are passing to the `expect` argument is different to the one currently persisted, and atomic reference expect it to be same:
`@param expect is the value you expect to be persisted when the operation happens` 

The problem here is that you are creating a new instance of the case class `Test`, try instead to pass the initial one like:

```
val t = Test(0)
val state = AtomicAny(t)
state.compareAndSet(t, Test(1))
``` 
or you could also just get the atomic value: 

```scala
val state = AtomicAny(Test(0))
state.compareAndSet(state.get, Test(1))
```

**Comment by fspillner** [comment]
You are right - I didn't read the documentation in detail. Thank you for your fast help.
