### ISSUE TITLE
Backpresure failure when converting Observable to Akka-Stream

### ISSUE THREAD

**Issue by squadgazzz** [monix/monix#1386]
Monix's Backpressure breaks down at this point.
Monix emits new events before the client gets any previous.
i.e. For a slow Subscriber first log gets 17 while the second one still has 2 only yet.

```
    val source = Source
      .fromPublisher {
        Observable
          .fromIterable(Stream.from(1))
          .takeWhile(_ < 50)
          .doOnNext(i => Task(println(s"monix: $i")))
          .toReactivePublisher(monix.execution.Scheduler.global)
      }
      .map { i =>
        println(s"akka: $i")
        i
      }

    val f = source
      .map { i =>
        Thread.sleep(5000)
        println(s"consumer: $i")
        i
      }
      .runWith(Sink.seq)

    val result = Await.result(f, 5.minutes)
```

Sample log:
```
monix: 1
akka: 1
monix: 2
monix: 3
monix: 4
monix: 5
monix: 6
monix: 7
monix: 8
monix: 9
monix: 10
monix: 11
monix: 12
monix: 13
monix: 14
monix: 15
monix: 16
monix: 17
consumer: 1
akka: 2
consumer: 2
akka: 3
consumer: 3
akka: 4
consumer: 4
akka: 5
consumer: 5
akka: 6
consumer: 6
akka: 7
.
.
.
.
```

**Comment by squadgazzz** [comment]
Looks like it's an Akka issue that is controlled not really well by input buffer setting https://doc.akka.io/docs/akka/current/stream/stream-rate.html#internal-buffers-and-their-effect
This should be documented in the Monix's guide.

**Comment by jvican** [comment]
> This should be documented in Monix's guide.

How do you want to document it? We don't have a guide to integrate Monix with Akka, so I struggle to see the right part where we'd like to document this kind of gotcha.

**Comment by alexandru** [comment]
@squadgazzz I just saw this issue. Indeed, this is how Akka Streams work.

Akka Streams has the philosophy that the emited events aren't special sources, and the protocol is there for back-pressure, not for safe handling of resources. This is actually the philosophy behind Reactive Streams, which handles back-pressure, not resources.

This actually has far-reaching implications. For example converting a `cats.effect.Resource` into a `Stream` isn't legal:

```scala
// This should not be legal ;-)
def fromResource[A](r: Resource[Task, A]): Source[A, NotUsed]
```

This is because an Akka Stream `Source`, when materialized, has no way of knowing whether the client is done with processing `A` or not.

Monix's `Observable` is actually better behaved IMO, as it introduces buffering only when needed (e.g. in `merge`, not `flatMap`), or only when explicit. This means you can use `Observable` to process stuff one by one. But the optional buffering in `Observable` is still problematic. So problematic that I'm thinking that we should not provide a conversion from `Resource` to `Observable` either.

Still, having a document on the `monix.io` website about how to integrate with Akka Streams would be pretty cool.

I have created a documentation ticket for it: #1426 

And will now close the issue, if you don't mind, since I'm trying to clean up the issue tracker :)
