### ISSUE TITLE
Missing interface for Eval/Trampoline in effect hierarchy

### ISSUE THREAD

**Issue by edmundnoble** [monix/monix#197]
There's no interface in monix-eval for types that capture synchronous, trampolined evaluation without errors. Examples include `Eval` in cats, `Trampoline` in scalaz, and `util.TailCalls` in the stdlib. `Deferrable[F]` almost fits except for the `Recoverable[F, Throwable]` supertype.

**Comment by alexandru** [comment]
@edmundnoble those types are experimental and thus far meant to fit the types exposed by Monix. Monix thus far doesn't expose more because it would end up duplicating Cats and Scala.

It is also incredibly hard to design type classes. Therefore in the interest of having usable integration with Cats and Scalaz, the types are now just the shims necessary for what Cats and Scalaz already provide.

This means that `Deferable` and `Recoverable` are gone for the moment. Upgrade to the latest version and you'll see. I am interested in providing more than the shims of Cats, so these types might be back, but the priority is releasing a stable 2.0 release that people can rely on.

That said I'm interested in your use-case. Are you looking for an abstraction over all these types?

Also, are you interested in helping with the design of these type classes? The timeline would be September 1st for the release of 2.0 (could happen right now, but waiting for people to come back from vacation), than possible improvements to those types could happen for 2.1.

**Comment by edmundnoble** [comment]
@alexandru I would be interested in contributing to the design of these typeclasses. Unfortunately I'm away from my development machine at the moment, but I think typeclasses entirely for abstracting over evaluation would have very little overlap with Scalaz and cats, though they'd still need shims. They might even be useful enough to be worth their own (small) library.

My use case is abstracting over trampolined functions so that I can add trampolined and partially trampolined (a la http://blog.higher-order.com/blog/2015/06/18/easy-performance-wins-with-scalaz/) recursion schemes to matryoshka, for a compiler I am writing. I'm also open to creating a monix-matryoshka integration which would (for example) allow emitting partial results of a recursion scheme to an observable, or using the monix-eval hierarchy to express asynchronous or potentially error-throwing recursions generically.

**Comment by alexandru** [comment]
@edmundnoble cool. Sorry, I've been away on vacation.

I already had a design in [Evaluable](https://github.com/monixio/monix/blob/500c9b4c82e364889db8be3768e1e819f05f7855/monix-eval/shared/src/main/scala/monix/types/Evaluable.scala) and [Deferrable](https://github.com/monixio/monix/blob/500c9b4c82e364889db8be3768e1e819f05f7855/monix-eval/shared/src/main/scala/monix/types/Deferrable.scala).

We can bring those back, but it's not so easy. Like I'd like some laws to accompany these type-classes. 

Another problem is how do you describe a type-class for something that produces a single result? This is the reason for the `Recoverable` super type, because you can then at least have `materialize`.  And because these types will live in `monix-types`, we can't have the conversion to `Task` either.

So again, how do you describe something that eventually produces a single result (Eval, Coeval, Task) and not something that can produce a whole stream (e.g. Observable)?

**Comment by alexandru** [comment]
@edmundnoble FYI there's a new branch where I'm bringing back some of my previous work: https://github.com/monixio/monix/tree/wip-eval-streams

In particular, there's a new [Enumerator](https://github.com/monixio/monix/blob/wip-eval-streams/monix-eval/shared/src/main/scala/monix/eval/Enumerator.scala) type that can use both `Task` and `Coeval` as the underlying mechanism for doing evaluation.

So there's now the [Deferrable](https://github.com/monixio/monix/blob/wip-eval-streams/monix-types/shared/src/main/scala/monix/types/Deferrable.scala) type-class and it no longer inherits from any `Recoverable` and it could be applied to Cats `Eval`.

Let me know what you think.

**Comment by alexandru** [comment]
This is no longer relevant, we dropped `monix-types` and moved on to `cats-core` and `cats-effect`. Closing.
