### ISSUE TITLE
Asynchronous Observable's cleanup functions

### ISSUE THREAD

**Issue by volth** [monix/monix#199]
`Task`s `doOnFinish(f: Option[Throwable] => Task[Unit])` accepts callback which allows chaining of asynchronous cleanup functions.

By contrary, `Observable`s functions suitable for resource cleanup  `doOnSubscriptionCancel(cb: => Unit)` `doOnTerminate(cb: => Unit)` accept callbacks which allows chaining only of synchronous cleanup functions.

Practical example: the first cleanup function sends the final message (for example https://www.postgresql.org/docs/9.5/static/sql-unlisten.html) andthen another cleanup function returns the connection to the connection pool. It can be easily done with `Task` but not so easy with `Observable`. Although Postgresql's LISTEN/UNLISTEN is clearly a case for `Observable`s not for `Task`s (as BEGIN/COMMIT can be)

**Comment by alexandru** [comment]
@volth couldn't think of a use case for observables, but you might be right. The Task doOnFinish is new and might make sense for observables as well. Will think about it.

**Comment by volth** [comment]
Well, ```doOnFinish``` with asynchronous callback is new in monix, but it is [at least 3 years old](https://github.com/scalaz/scalaz/blame/series/7.3.x/concurrent/src/main/scala/scalaz/concurrent/Task.scala#L56) in scalaz. So it can be seen as the established approach rather than as an experimental one.

**Comment by ajaychandran** [comment]
A simple example to demonstrate that nested cleanup functions are not being executed.

```scala
Observable(2)
  .doOnTerminate(println("upstream terminated"))
  .flatMap(i => Observable(0 until i: _*).doOnTerminate(s"downstream $i terminated"))
  .foreach(println)
```

**Result**
```
0
1
upstream terminated
```

**Expected**
```
0
1
downstream 2 terminated
upstream terminated
```

**Comment by alexandru** [comment]
@ajaychandran dude, in that piece of code you have a problem: the child's `doOnTerminate` contains a pure expression that doesn't do anything, i.e. `println` is missing.  Honest mistake, I do it too :-P

**Comment by alexandru** [comment]
@volth the `doOnSubscriptionCancel` can't receive a function returning a `Task`, because having that `Task` wouldn't do anything useful. This is because when the subscription is canceled, the downstream no longer receives any signal.

The only point of working with `Task` is to ensure some order of execution. In the case of `Task.doOnFinish` the resulting `Task` does not complete until the cleanup function completes. Now we could do the same thing for `Observable`, though I think it is less useful than with `Task`. But nevertheless I can see instances where this would be useful. So the behavior should be that the `onComplete` and/or `onError` events should not be signaled downstream until the given cleanup `Task` has finished.

Now, the current methods stay synchronous. I know people have been doing it for years in Scalaz, but these methods are actually from ReactiveX. But we can introduce alternatives that use `Task`. So: 

1. `doOnTerminate` => `doTaskOnTerminate`
2. `doOnComplete` => `doTaskOnComplete`
3. `doOnError` => `doTaskOnError`

Also notably, implementing this for the following does not make sense, because in these cases the downstream subscribers are not receiving a completion event, so there's nothing to delay:

1. `doOnDownstreamStop`
2. `doOnSubscriptionCancel`

Will keep this open. If you are interested in working on this, let me know :-)

**Comment by alexandru** [comment]
`Observable` now have `doOn*` versions suffixed with `Eval` or `Task` and that take `Task` or `F[_] : Effect` params.
