### ISSUE TITLE
Java 8 compatibility: Add conversions for Completable Future

### ISSUE THREAD

**Issue by Diagoras** [monix/monix#221]
I'm thinking `Task.fromCompletableFuture` and `def runAsyncAsJava: CompletableFuture`, both being pretty similar to the existing `Task.fromFuture` and `def runAsyncForJava: Future`. Not sure what the best way to add new methods is without cluttering up `Task` and maintaining Scala.js compatibility, though.

**Comment by alexandru** [comment]
The problem isn't only Scala.js compatibility, but compatibility with Java 6 and 7. [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) is available only starting with Java 8 and that's a problem, since Java 6 and 7 support will be maintained for as long as Scala 2.11 is in use. And that will be a long time, since Android has not been migrated to Java 8, which makes Scala 2.11 a long-term-support release.

We can only provide such support as a separate project, because we can't have such functions on the `Task` type or its companion object. This means a `monix-java8`. Which could provide extension methods ...

```scala
import monix.java8.extensions._

val task = Task.fromCompletableFuture(cf)
task.runAsync.asJava
```

Btw, as in the example, I wouldn't do a `task.runAsyncAsJava`. It would be much better to convert `CancelableFuture` instead of `Task`.

This project could then later expand its purpose to providing [NIO integration](https://docs.oracle.com/javase/tutorial/essential/io/fileio.html), though NIO is also available for Java 7, so we could also be talking about a `monix-java7`.

**Comment by alexandru** [comment]
Given that Scala 2.12 requires Java 8, this should be added for Scala 2.12 only.
