### ISSUE TITLE
Task.traverse does not have a nondeterministic analogue

### ISSUE THREAD

**Issue by mutantmell** [monix/monix#249]
The Future api in the base library provides a parallel traverse, and Task should have a parallel version as well.

Task already has a parallel and a sequential implementation of sequence: 

parallel: https://github.com/monixio/monix/blob/master/monix-eval/shared/src/main/scala/monix/eval/Task.scala#L886
sequential: https://github.com/monixio/monix/blob/master/monix-eval/shared/src/main/scala/monix/eval/Task.scala#L852

monix should be able to use the same basic scheme to provide a parallel traverse.

**Comment by alexandru** [comment]
@mutantmell to tell you the truth, I don't really see the point in `traverse` at all, at least in its current incarnation.

I mean, it has value in its current incarnation when the given `M[_]` collection has lazy behavior (e.g. Stream or Iterable) and thus you avoid evaluating the current `f(a): Task` until needed. But then a version that does things in parallel needs to evaluate the whole thing at once, so that argument is gone.

Could be useful, but now I'm not seeing it. Could you provide a use-case for a parallel traverse?

**Comment by alexandru** [comment]
@mutantmell any further thoughts on this matter? Do you have a use-case for a parallel traverse?

**Comment by mutantmell** [comment]
We are currently using the stdlib Future library for most of our code, and many of the frameworks we use (e.g. akka http, slick, etc.) return/require Futures.  We are very i/o heavy in our service, with lots of blocking (waiting for data to return from a database, waiting for the result of a web call, etc.).  We use Future.traverse to mitigate this -- while the first request in a list is blocked, we start evaluating the second value, etc, allowing us to overlap the blocking calls as much as possible.

Adding a parallel traverse to monix would help assist a transition from just stdlib Futures to using monix Tasks - we could wrap Futures in Tasks where libraries provide them, and still have the ability to overlap blocking calls.

**Comment by alexandru** [comment]
@mutantmell I understand, but assuming you have an `M[A]` list that you want to convert into a `Task`, I guess you're doing something like this:

```scala
def f(a: A): Future[B] = ???
val list: List[A] = ???

val future: Future[List[B]] =
  Future.traverse(list)(f)
```

So my question is, why not do this instead:

```scala
def f(a: A): Task[B] = ???
val list: List[A] = ???

val task: Task[List[B]] =
  Task.gather(list.map(f))
```

Isn't it the same thing?

BTW, I wouldn't mind adding a parallel traverse at all, except that I don't know how to name the thing :-) The name for `gather` and `gatherUnordered` come from Scalaz, so there's precedent there. 

Can you think of a good name for it?

**Comment by mutantmell** [comment]
Yes, those would have the same functionality for us.  We use `traverse` more heavily than `map => sequence/gather` because it fits better with many of the frameworks and patterns that we use (aka it removes noise from the implementation).

As for a name, how about `wander`/`wanderUnordered`?  It plays on the `traverse` name, and doesn't overlap with other iterator functions.

**Comment by alexandru** [comment]
@mutantmell Nice naming :-) Thesaurus? :-P

Would you be willing to contribute a PR?

BTW, I changed `gatherUnordered` to no longer play on `CanBuildFrom` and instead have this signature:

```
def gatherUnordered[A](in: TraversableOnce[Task[A]]): Task[List[A]]
```

The reason is because I optimized normal `gather` enough that the old version didn't have an advantage anymore, so to make this one worth-while, I made this one to have non-blocking behavior by means of an `Atomic[List[A]]`.

Just something to be aware of.

**Comment by mutantmell** [comment]
Ok, sure. I'll get to it when I have time.

Do you have something more complex in mind than implementing it in terms of gather(unordered)?

**Comment by alexandru** [comment]
No, it can be described in terms of `gather` just fine.
