### ISSUE TITLE
Feature request: add destroy to Scheduler

### ISSUE THREAD

**Issue by erikvanoosten** [monix/monix#266]
There is currently no way to close a scheduler, you always need to close the underlying executioncontext directly. Unfortunately this does not work for schedulers that are created with the convenience methods like `Scheduler.singleThread`.

Please add a `shutdown` and/or `shutdownNow` method to `Scheduler`.

**Comment by alexandru** [comment]
@erikvanoosten that won't happen on the `Scheduler` interface.

I guess you have a use-case like starting a `singleThread` scheduler, executing stuff on it, then shutting down it down at some point, but shutting down schedulers is very error prone in combination with Monix's abstractions like `Task` or `Observable`. This is why all schedulers in Monix are initialized with `daemon` threads. And for `Scheduler.io` for example you  don't even need to shut it down, since those threads are going to expire, you can just let the garbage collector to collect it. I'm also adding a new `Scheduler.cached` constructor where you can fine-tune the timeout, etc.

The other and more serious problem is that in some cases you have no way to shutdown a scheduler. On top of Javascript you definitely can't shutdown its `setTimeout`. And it would be incredibly error-prone to let users shutdown `monix.execution.Scheduler.Implicits.global`.

That said I'm inclined to add a `SchedulerService` interface, just like how Java has `Executor` vs `ExecutorService`. Maybe next version.

**Comment by alexandru** [comment]
So what do you think, would a `SchedulerService` returned by builders such as `singleThread` work for you?

**Comment by erikvanoosten** [comment]
I am not sure. The Java `Executor` vs `ExecutorService` has always confused me. When do you use which (to be honest, I never tried to look it up).

Its good to know that all the convenience methods like `singleThread` use daemon threads. The use case I had in mind is unit tests. For each component we easily have a dozen tests that spin up a scheduler with one or a few threads (though we direct synchronous execution when we can). I would like it if the total thread count does not go up with a growing number of tests.

**Comment by alexandru** [comment]
@erikvanoosten feature is on master and I would appreciate if you provided some feedback.

I have provided `monix.execution.schedulers.SchedulerService` which has `shutdown()`, `isShutdown`, `awaitTermination` and `isTerminated` methods. And the `Scheduler` builders that are returning schedulers built on top of Java executors are now returning this new `SchedulerService` type. 

You can play with `2.2.0-SNAPSHOT`, the latest one published has this feature, however don't depend on it on anything other than playing with it.

Cheers,
