### ISSUE TITLE
ConnectableObservable cannot be consumed by both foreach and consumeWith

### ISSUE THREAD

**Issue by buaya91** [monix/monix#290]
Hi, I discovered there's some difference between consuming stream with `subscribe` vs `consumeWith` or `foreach`

[test case PR](https://github.com/buaya91/monix/pull/1)
1st test case failed as the consumeWith did not run, I am not sure if this is the expected behaviour, or did I use the testframework wrongly?

I am expecting all these 3 means of consuming stream to yield same result.

**Comment by alexandru** [comment]
@buaya91 please test with the latest `2.2.0-M1` release, the issue should no longer be reproducible.

As I said, the problem is that in `2.1.x` the behavior of `foreach` and of `consumeWith` is to do async execution, so in effect their underlying `subscribe` operation happens after `connect`. See issues #288 and #289.

I have also introduced a new Rx-inspired operator called `publishSelector` that makes transforming observables possible without having to deal with `ConnectableObservable` at all; see #295

**Comment by buaya91** [comment]
@alexandru I just tried to run with latest master branch which from commits include #288 #289

but the test still failed

To run test case
`testOnly monix.reactive.observables.ConnectableObservableTestCase`

with my [PR](https://github.com/buaya91/monix/pull/1)

**Comment by alexandru** [comment]
@buaya91 I finally got around to seeing your tests and your first test was wrong - the `runAsync` on the task returned by `consumeWith` was happening after `connect`, so it was receiving the events because all the events were streamed already.

I now pushed a test proving that `consumeWith.runAsync` and `foreach` on `ConnectableObservable` both subscribe before the call to `connect()` if executed before `connect()`.
