### ISSUE TITLE
monix 2.2.1 not found in maven

### ISSUE THREAD

**Issue by golem131** [monix/monix#310]
https://repo1.maven.org/maven2/io/monix/monix_2.11/2.2.1/monix_2.11-2.2.1.jar - 1 not found

**Comment by alexandru** [comment]
@golem131 the `io.monix.monix` package is a "meta" projects containing sub-projects and does not need a JAR because it would be completely empty. The Maven format allows for such artifacts.

In case you're using Coursier package management, please add your concern on this issue: https://github.com/alexarchambault/coursier/issues/429
