### ISSUE TITLE
Expose BehaviorSubject value

### ISSUE THREAD

**Issue by jchapuis** [monix/monix#363]
It would be sometimes useful to have a thread-safe access to BehaviorSubject's current value, for instance in stateful situations such as in the UI or in general for low-overhead out-of-monad imperative access.

Interestingly, in .NET they added support for direct value access in a second step, it wasn't part of the initial version either. It is exposed through a c# property Value which is threadsafe (but you can still have a race condition with OnNext). It throws the exception if there was an OnError. There is also a TryGetValue which return false if the subject had been disposed (cancelled). You can find the code here for reference: https://github.com/Reactive-Extensions/Rx.NET/blob/d14220c30637f42aeb15b7db644e9f524eb10a03/Rx.NET/Source/src/System.Reactive/Subjects/BehaviorSubject.cs

Note that this could be combined with a `Var` concept, see #279

**Comment by alexandru** [comment]
Hi @jchapuis, the problem with our `BehaviorSubject` is that it does back-pressure and users are not supposed to use it directly, because it's difficult to use, due to its back-pressure protocol. The subjects themselves get wrapped in `ConcurrentSubject` or in `Pipe` (which is a factory), which adds a concurrent buffer in front of the subject to make it safe for synchronous usage. This is different from .NET, which does not have a back-pressure protocol.

And `ConcurrentSubject` and `Pipe`, well the problem is that these are generic wrappers and we don't have a `ConcurrentBehaviorSubject` or a `PipeBehavior`. 

With issue #279 we introduced `Var`, which is basically a `ConcurrentBehaviorSubject` that exposes the current value. Not sure if that's enough, but I don't think we can do more than that. And yes `Var` is not a `Subject`, but it is an `Observable` and that should be enough.

**Comment by jchapuis** [comment]
Hi @alexandru ok, thanks for the informative response!
