### ISSUE TITLE
resolution problems

### ISSUE THREAD

**Issue by antonkulaga** [monix/monix#379]
I constantly have issues with monix resolution. For instance, in spark-notebook if often fails to find it ( https://github.com/spark-notebook/spark-notebook/issues/889 ), have you checked that the 2.3.0 version is published properly?

**Comment by alexandru** [comment]
@antonkulaga sorry to hear that, but the packages get published to Sonatype and Maven Central and it's out of my hands.

You can check the packages on Maven Central's links, e.g...

- https://repo1.maven.org/maven2/io/monix/
- https://repo1.maven.org/maven2/io/monix/monix_2.11/
- https://repo1.maven.org/maven2/io/monix/monix-execution_2.11/
- https://repo1.maven.org/maven2/io/monix/monix-eval_2.11/
- https://repo1.maven.org/maven2/io/monix/monix-reactive_2.11/
- https://repo1.maven.org/maven2/io/monix/monix_2.12/
- https://repo1.maven.org/maven2/io/monix/monix-execution_2.12/
- https://repo1.maven.org/maven2/io/monix/monix-eval_2.12/
- https://repo1.maven.org/maven2/io/monix/monix-reactive_2.12/

Everything is there and there's nothing else we can do.

Note that the base package (i.e. `io.monix % monix`) is only a POM artifact, meaning that it's missing a JAR file, since it would be empty. It's why if you'll take a look at [monix_2.11-2.3.0.pom](https://repo1.maven.org/maven2/io/monix/monix_2.11/2.3.0/monix_2.11-2.3.0.pom) for example you'll see:

```xml
<packaging>pom</packaging>
```

This has caused problems with [Coursier](https://github.com/coursier/coursier) in the past. My guess is that you should push this issue to the projects that are doing the dependency resolution.
For example I see that `coursier/coursier-cache` is being used and it might actually be to blame for it.

Another thing you could try is to depend on `monix-reactive` instead of `monix`. The base `monix` is a meta-package that brings in the sub-projects as dependencies, but at this point in time it is equivalent with depending on `monix-reactive`.

Hope that helps.
