### ISSUE TITLE
TaskCircuitBreaker can retry protected Task's

### ISSUE THREAD

**Issue by kdrakon** [monix/monix#382]
While using the `TaskCircuitBreaker` the first time, my intuition was that I could submit (i.e. protect) a Task to the breaker and have it perform retries if the circuit was open. At first, I did something like this:
```
MyBreaker.protect(someTask).onErrorRestartIf(???)
```
where `???` would have some logic where I would determine if my Task should be re-attempted (e.g. a counter in one basic use case). Although this works, it wasn't optimal as the restarts would hammer the circuit breaker regardless of the circuit being known to be open. Ideally, it would be useful to have the circuit breaker restart protected tasks based on the internal reset timeout of the circuit when it is open.

I propose an enhancement that the circuit breaker be able to handle retries of protected tasks *as well* as the ability to delay their execution based on the configured and running reset timeout.

**Comment by kdrakon** [comment]
I've submitted a proposed PR for this change. It adds the following methods:
```
  def protectWithRetry[A, B >: A](task: Task[A], maxRetries: Long, onErrorHandleWith: PartialFunction[Throwable, Task[B]])(implicit s: Scheduler): Task[B] 
  def protectWithRetry[A](task: Task[A], maxRetries: Long)(implicit s: Scheduler): Task[A] 
  def protectWithRetry[A, B >: A](task: Task[A], onErrorHandleWith: PartialFunction[Throwable, Task[B]])(implicit s: Scheduler): Task[B] 
  def protectWithRetry[A](task: Task[A])(implicit s: Scheduler): Task[A]
```
Further explanations are provided in the ScalaDoc.

**Comment by alexandru** [comment]
@kdrakon this is a tough problem and has been on my mind. The problem with restarting logic is that it tends to be very custom, depending on use-case.

For example restarting immediately isn't ideal, as you've seen, but maybe a better solution would be to do exponential backoff, e.g. retry in 100ms, 200ms, 400ms, 800ms, 1.2 secs, etc.

And I haven't added any helpers for doing exponential backoff on `Task` because, well, there are multiple ways of doing it.

Another solution on my mind is to maybe make the `TaskCircuitBreaker` put those failing tasks to sleep instead, for as long as the circuit breaker is open. I'm still thinking.

I'm very sorry for the delay in replying, it's been holiday season and then forgot about it; let me know if your thoughts changed since July.

**Comment by kdrakon** [comment]
Hi @alexandru, sorry about my also delayed response; some family emergency stuff came up and everything fell off the radar. Not sure if I can muster the effort to pick this up again, but please feel free to take whatever you desire from the branch.

**Comment by alexandru** [comment]
The `CircuitBreaker` was refactored and moved in `monix-catnap`.

It now has a facility for waiting on the circuit breaker to be closed again and should solve your use-case.

See docs: https://monix.io/api/3.0/monix/catnap/CircuitBreaker.html
