### ISSUE TITLE
Growing RAM-usage for groupBy operation

### ISSUE THREAD

**Issue by valenterry** [monix/monix#393]
Using `groupBy` can consume quite a bit RAM. I tried to group some tuples by there first element and use some operation (here sum) on their second element for each group:

```
import monix.reactive.Observable
import monix.execution.Scheduler.Implicits.global

import scala.concurrent.Await
import scala.concurrent.duration.Duration


object Test extends App {
  val observable: Observable[(String, Int)] = Observable
    .repeat(("A", 1), ("B", 2), ("C", 3), ("D", 4))
    .take(40000000)
    .groupBy(_._1)
    .mapAsync { group =>
      group
        .foldLeftL(0) { case (sum, (character, nextNum)) =>
          sum + nextNum
        }
        .map( sum => (group.key, sum) )
    }

  Await.result(observable.foreach(println), Duration.Inf)
}
```

Works as expected and outputs (after a bunch of seconds):
```
(A,10000000)
(B,20000000)
(C,30000000)
(D,40000000)
```

But RAM usage is growing with every additional element that is processed, reaching some GB quite fast.
Tested both with Monix 2.3.0 and 3.0.0-22bf9c6 on Scala 2.11.

**Comment by alexandru** [comment]
Thanks for the report.

On first glance, I don't see why this could happen, so we might have a problem.
Will need to be investigated.

**Comment by alfonsorr** [comment]
Hi, i don't believe it's a bug, it looks more a optimization problem. @valenterry , in your case you are creating a single data structure with all the data grouped (the 40k elements, and then add them), so it's normal the ram grow.
In this case would be much better to use a fold left to sum the elements in the moment it arrives, so you only carry a single int element.
```
object Timer {
  def withTimer(f: () => Unit) = {
    (1 to 3).foreach(_ => f()) //warmup
    println((1 to 5).map( _ => {
      val start = System.nanoTime()
      f()
      val end = System.nanoTime()
      end - start
    }).map(a => {println(a); a}).sum)
  }
}

object Test extends App {
  val observable: Observable[(String, Int)] = Observable
    .repeat(("A", 1), ("B", 2), ("C", 3), ("D", 4))
    .take(40000000)
    .groupBy(_._1)
    .mapAsync { group =>
      group
        .foldLeftL(0) { case (sum, (character, nextNum)) =>
          sum + nextNum
        }
        .map( sum => (group.key, sum) )
    }


  Timer.withTimer(() => Await.result(observable.foreach(println), Duration.Inf))
}


object Test2 extends App {
  val observable: Task[Map[String, Int]] = Observable
    .repeat(("A", 1), ("B", 2), ("C", 3), ("D", 4))
    .take(40000000)
    .foldLeftL(Map[String, Int]())((acum, e) => acum + (e._1 -> (e._2 + acum.getOrElse(e._1, 0))))

  Timer.withTimer(() => Await.result(observable.foreach(println), Duration.Inf))
}
```

And the memory usage of each one:
![test1](https://user-images.githubusercontent.com/15030451/29210440-eb735938-7e93-11e7-95a7-3e7063141059.png)
![test2](https://user-images.githubusercontent.com/15030451/29210447-efa9b1e6-7e93-11e7-8d5e-267d07a5e431.png)

If your case has an different behavior than this one, it could be a  bug. In other case, this is the expected case.

**Comment by alexandru** [comment]
@alfonsorr thanks a lot for investigating this, I'm currently busy with something else at the moment.

Rest assured @valenterry I haven't forgotten about it.

**Comment by valenterry** [comment]
@alfonsorr I agree, it will not produce incorrect results, so maybe it should be considered a performance improvement. On the other hand, from the theoretical perspective, there is no reason why anything needs to be accumulated in RAM in this case.

We get a stream of elements and group them *but* we immediatly work with each group and fold the group into one element. There is no need for the elements to be put into a list for each group before each of these lists can be processed. Therefore, more elements should not result in growing RAM usage in the optimal case.

I'm not sure though if this only works in my specific case or generally when using streaming-groups.

More generally, if I have a stream of elements, a function that assigns a identifier/key to every element and a function `(Key -> Elem, Map[Key, Result]) => Map[Key, Result]` then I am able to process the stream with constant RAM usage. But doing it manually is tedious and having Monix doing the grouping-work would be really nice. I will take a look into this later on.

**Comment by oleg-py** [comment]
Hope late is better than never :)

@alexandru @valenterry it seems it's by design, although fairly subtle.

`mapAsync` (`mapTask` in 3.x) is *serial*, which means the resulting `Observable` will wait for the task to complete before starting processing another one to ensure the ordering of items is preserved. That means waiting for result of `foldLeftL`, which only completes when the `Observable` of your group completes, and *that* for `groupBy` can only happen when the source completes - which in your case is when you finally emit 40 millions of tuples. Until that happens, you do not start processing groups for B, C and D, which means they will be buffering their items (per documentation) by means of `ArrayBuffer`, each reaching 10 millions in size with a handful of reallocations happening.

It can be seen by adding a `println` to your `mapAsync` call:
```scala
  .mapAsync { group =>
    println(s"Processing group ${group.key}")
```

Will result in the following output:
```
Processing group A
(A,10000000)
Processing group B
(B,20000000)
Processing group C
(C,30000000)
Processing group D
(D,40000000)
```

And the first line will show up immediately, while other 7 will show up after a while (but within a short time between each other)

So
> we immediatly work with each group and fold the group into one element

is not true, the code waits for work on each group to complete before starting to process another.

---

To combat this, you can use `Observable#mergeMap`. It does not care about preserving order, and thus is able to start processing immediately:

```scala
object Test extends App {
  val observable: Observable[(String, Int)] = Observable
    .repeat(("A", 1), ("B", 2), ("C", 3), ("D", 4))
    .take(40000000)
    .groupBy(_._1)
    .mergeMap { group =>
      println(s"Processing group ${group.key}")
      group
        .foldLeftF(0) { case (sum, (character, nextNum)) => // like foldLeftL, but gives a single-element observable
          sum + nextNum
        }
        .map( sum => (group.key, sum) )
    }

  Await.result(observable.foreach(println), Duration.Inf)
}
```

Output:

```
Processing group A
Processing group B
Processing group C
Processing group D
(A,10000000)
(B,20000000)
(C,30000000)
(D,40000000)
```
Now 4 first lines pop up immediately, and the RAM usage is much saner. The order of outputs is not guaranteed anymore, in this case is just an implementation artifact (`groupBy` uses scala's immutable map, which up to a size of 4 preserves the ordering of elements, see `scala.collection.immutable.Map4`; adding group "E" will turn it into a hashmap, ruining the ordering)

Screenshots from JProfiler:
[mapTask version](https://i.imgur.com/y2Lx43r.png), reaching 1GB and with huge peaks
[mergeMap version](https://i.imgur.com/85io9fk.png), peaking at 60Mb in the very beginning and staying low and even.

---

That being said, as I was debugging, I noticed the buffers were still allocated in `mergeMap` version until the processing actually started, albeit much smaller ones (only 48 elems).

**Comment by valenterry** [comment]
Thanks for the detailed explanaition. It's not a bug and I will therefore close the issue. :)

**Comment by alexandru** [comment]
Thanks @valenterry — personally I'm not happy about `groupBy` because it's confusing, but given back-pressure and the scenario `groupBy` is most likely to be used (e.g. `groupBy(_.key).mergeMap`), this might be the best we can do.

But if you have suggestions for alternatives, please share them.

**Comment by alexandru** [comment]
@oleg-py forgot to make an observation on your comment:

> I noticed the buffers were still allocated in mergeMap version until the processing actually started, albeit much smaller ones (only 48 elems).

The `mergeMap` operation also does buffering. Because in `mergeMap` you end up with multiple producers pushing data into the same back-pressured consumer, buffering is inevitable and it's much saner to allocate a fixed buffer upfront, then working with `lastAck.flatMap` or `.syncOnContinue` or other solutions like that.
