### ISSUE TITLE
Question: Task.Error

### ISSUE THREAD

**Issue by NeQuissimus** [monix/monix#428]
Hi,

I am writing tests against an application that uses Monix (mostly `Task`).
I am in a bit of a pickle now :)
I would like to test whether a constructed `Task` is failed without running/materializing it.
The thing is that running it would incur quite a few operations.

So now I am doing this:
```scala
val task: Task[Result] = ...
task.getClass.getCanonicalName =!= "monix.eval.Task.Error"
```

Clearly, not an ideal solution :D 
Since `Task.Error` is private to `monix.eval` I cannot pattern match.

So either I am missing something obvious or there is (currently?) no better way.
(Other than refactoring what I am looking at...)

**Comment by alexandru** [comment]
@NeQuissimus there's unfortunately no good solutions to what you want to do.

The problem is that `Task` behaves like function, not being the result of a computation itself. And you can't see if a function is going to fail before actually running it.

`Task.Error` is private because it's an implementation detail. And `Task.Error` isn't the only way to express immediate errors. You can also have `Task.eval(throw e)` or `Task.Error(e).map(id)` or other combinations.

This is basically the difference between `Future` and `Task`. A `Task` does not represent a result of some computation, but the computation itself.

**Comment by NeQuissimus** [comment]
Yeah, that's the conclusion I came to... I may just leave the hack in place where I want to test that a mattern patch shortcuts the Task...
