### ISSUE TITLE
java.lang.NoClassDefFoundError: monix/eval/Task$

### ISSUE THREAD

**Issue by aphasingnirvana** [monix/monix#448]
While implementing Tasks in Scala ran into this error every time I run it. 
Added to sbt using the following command from Maven Repo
> "io.monix" % "monix_2.12" % "2.3.0" pomOnly()

Tried even monix-eval but didn't work either.

I'm using 
> scalaVersion := "2.11.9"

What could be the issue @alexandru ?

**Comment by alexandru** [comment]
@aphasingnirvana `NoClassDefFoundError`s usually happens due to classpath issues.

Check if the `monix-eval` is available in your classpath on execution.
Also see [sbt-dependencies-graph](https://github.com/jrudolph/sbt-dependency-graph), an SBT plugin with which you can check who depends on what, such that you can spot potential conflicts.

**Comment by aphasingnirvana** [comment]
@alexandru Yes, I resolved it by making an [uber jar](https://stackoverflow.com/questions/28459333/how-to-build-an-uber-jar-fat-jar-using-sbt-within-intellij-idea) instead, thanks for your help.
