### ISSUE TITLE
Improve performance of Monix Task, relative to competition

### ISSUE THREAD

**Issue by alexandru** [monix/monix#452]
@jdegoes is presenting the following slide at [scala.io](https://scala.io):

![performance](https://user-images.githubusercontent.com/11753/32175131-a29049d2-bd8c-11e7-9d05-7c245a59b430.jpg)

I'm happy about the progress that Scalaz is making, but for Monix second place in unacceptable.
So another round of optimizations is coming.

#gameon

**Comment by jdegoes** [comment]
I'm delighted to see my work was the inspiration for this, and to see the whole ecosystem working together for an outcome that will benefit the _entire_ Scala community. We're in this together. 😄 

_P.S._ Good luck. 😉

**Comment by fwbrasil** [comment]
@jdegoes is the benchmark code available somewhere? I'd love to see these numbers compared to https://github.com/traneio/future :)

**Comment by jdegoes** [comment]
@fwbrasil It'll be published Nov 16th with the PR. However, I tweeted the left-associated bind benchmark code some time ago. Have you compared to Monix?

You implemented in Java which is a better decision. If I need to extract more performance, I will do the same thing. The Scala compiler is horribly dumb and some choices cannot be worked around.

**Comment by fwbrasil** [comment]
@jdegoes I've compared to Monix but decided to remove the benchmarks because I wasn't sure it was a fair comparison. Take a look at https://github.com/traneio/future/issues/1

We've been porting many of the traneio future optimizations into the Twitter Future, so maybe it's worth comparing to it. More recently, I've been collaborating with Viktor to optimize the Scala Future as well: https://docs.google.com/document/d/1f3oBH-Nh_BZtd6zJxtW41TX3frnlyamC7dG7QmVIDU4/edit?usp=sharing

> You implemented in Java which is a better decision. If I need to extract more performance, I will do the same thing. The Scala compiler is horribly dumb and some choices cannot be worked around.

Yeah, that was one of the reasons for implementing it in Java.

Why only publish on Nov 16th? Isn't this work a OSS branch that people could collaborate on? To be honest, I find it unfair to publish benchmark results without providing the source code.

**Comment by alexandru** [comment]
The execution model of a `Future` data type is usually a little different than that of a `Task` / `IO` data type, because with a `Future` the `flatMap` chains aren't that long, whereas with a `Task` / `IO` you end up composing whole programs with its combinators and then trigger the execution (ideally) only once.

This is why in Monix the `runAsync` part (`unsafePerformIO`) is fairly expensive due to having to initialize some needed values, but I optimized it a little recently by delaying that initialization until the first async boundary.

@fwbrasil that said Trane's `Future` implementation looks awesome in terms of performance, it's an inspiration actually, I still rely on Scala's `Future` a lot and in my mind these data types are complementary and it's awesome that you and Viktor have been collaborating.

**Comment by jdegoes** [comment]
@fwbrasil 

> We've been porting many of the traneio future optimizations into the Twitter Future, so maybe it's worth comparing to it

I include Scala's `Future` mainly for reference, because so many programmers use it. Due to its effectful nature, `Future` is not suitable for functional programmers. The other two implementations, Cats IO and and Monix Task, are both viable candidates for functional programmers.

> Why only publish on Nov 16th? Isn't this work a OSS branch that people could collaborate on? To be honest, I find it unfair to publish benchmark results without providing the source code.

As an open source contributor yourself, please remember that it's my own personal code, which I work on unpaid and in my spare time between my day job, family, and non-profit work, and I will publish it when I have planned to publish it, as part of a talk I am doing November 16. 

I don't owe anyone the benchmarks at any point in time–let alone right now. My time belongs to exactly one person: me. I do, however, appreciate your interest and hope you find the code useful, when I release it as planned on November 16th.

@alexandru 

> The execution model of a Future data type is usually a little different than that of a Task / IO data type, because with a Future the flatMap chains aren't that long, whereas with a Task / IO you end up composing whole programs with its combinators and then trigger the execution (ideally) only once.

💯 

The flatMap benchmark in Trane also looks like it's testing a linear chain of futures, not a recursively-built (branching) tree as would be common in a functional program.

**Comment by fwbrasil** [comment]
@alexan

**Comment by fwbrasil** [comment]
@alexandru I wouldn't invest time in something that can turn out to be a wrong or biased set of benchmarks. I wouldn't be surprised if @jdegoes isn't using jmh or hasn't considered how the JIT interferes with the results. For instance, it's possible that the JIT is making the first benchmark a no-op.

> The execution model of a Future data type is usually a little different than that of a Task / IO data type, because with a Future the flatMap chains aren't that long, whereas with a Task / IO you end up composing whole programs with its combinators and then trigger the execution (ideally) only once.

I'm not sure why you think this is the case. It's pretty common to see long `flatMap` chains using Future in our systems at Twitter. That's actually the common case.

**Comment by alexandru** [comment]
> I'm not sure why you think this is the case. It's pretty common to see long flatMap chains using Future in our systems at Twitter. That's actually the common case.

Oh, I'm sure there are such use-cases. Plus the original use-case which triggered the optimization of `Future` to not leak memory in long `flatMap` chains (in [this PR](https://github.com/scala/scala/pull/2674), inspired by Twitter's Future actually) was with usage of [Play's Iteratees](https://github.com/playframework/playframework/issues/1084).

However with `Future` you end up extracting values out of its context way more often, via `onComplete` or `Await.result`. It goes with the territory, `Future` having strict behavior.

Was mentioning that as an interesting observation because Monix's `runAsync` has to do some initialization that's not relevant in the context of a `Future` implementation and that can be expensive, compared with triggering an `onComplete` on a `Future`. On `master` I delayed initialization for as long as possible, but it's still not enough of course.

**Comment by alexandru** [comment]
First batch of optimizations merged in https://github.com/monix/monix/pull/474 — porting the optimizations I did in `cats-effect`.

**Comment by alexandru** [comment]
The improvements I've made in the two batches referenced above are pretty good, having solved some clear bottlenecks.

I'm not sure if we managed to reach or exceed Scalaz 8's IO in performance, because testing against it is difficult without a released version. I have some other ideas in mind, but for the time being I'm no longer interested in further work because of other priorities, plus performance optimizations are exhausting 😐

Will resume once Scalaz 8 has a released version.
