### ISSUE TITLE
Observables created using `concat` don't get canceled

### ISSUE THREAD

**Issue by igstan** [monix/monix#468]
Consider the following snippet:

```scala
import scala.concurrent._, duration._
import monix.reactive._
import monix.execution._, Scheduler.Implicits.global

val a = Observable.now(1L)
val b = Observable.interval(1.second)
val c = a ++ b
val d = c.foreach(println)

d.cancel() // Doesn't cancel the "interval" observable.
```

I would have expected the `d.cancel()` call to cancel the right-hand observable of the `++` operation, but it doesn't.

This seems to be a problem with all observables created using `concat` or one of its incarnations.

It only happens with the observable on the right. The left one gets canceled:

```scala
import scala.concurrent._, duration._
import monix.reactive._
import monix.execution._, Scheduler.Implicits.global

val a = Observable.interval(1.second).map(_ => "1st")
val b = Observable.interval(1.second).map(_ => "2nd")
val c = a ++ b
val d = c.foreach(println)

d.cancel() // Works as expected.
```

**Comment by alexandru** [comment]
It is because of: `stateRef.lazySet(WaitOnActiveChild)` — see current commit.

The problem is that the logic is based on `getAndSet`. When you do a `getAndSet`, it's an optimistic update done with the knowledge that you can revert it.

However in this case we have a loophole related to cancellation. That instruction I mentioned above is "ordered" in relation with the subscriber and what happens in `onNext` / `onComplete` / `onError`, but not in regards to cancellation itself, which is completely concurrent. So the story is that when the above instruction happens, the current cancellation state gets deleted.

The fix closes this problem, but now I'm worried that we'll have performance regression due to the `getAndSet` being obviously more expensive than a `lazySet`. Shouldn't be dramatic though.
