### ISSUE TITLE
scan of Observable and Iterant are not consistent with stdlib

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#522]
Standard library `scan` yields initial element at the beginning of resulting collection:

```scala
// List(0, 1, 2, 3)
List(1, 1, 1).scan(0)(_ + _)
```

While in monix, neither `Observable` nor `Iterant` do:

```scala
import monix.eval.Coeval
import monix.tail.Iterant

// List(1, 2, 3)
Iterant[Coeval].of(1, 1, 1)
  .scan(0)(_ + _)
  .toListL
  .value
```
and
```scala
import monix.reactive.Observable

import scala.concurrent.Await
import scala.concurrent.duration.Duration
import monix.execution.Scheduler.Implicits.global

val r = Observable(1, 1, 1)
  .scan(0)(_ + _)
  .toListL

// List(1, 2, 3)
Await.result(r.runAsync, Duration.Inf)
```

I'm not sure if it is a bug or intentional, but IMO it is at least worth being explicitly documented.

**Comment by alexandru** [comment]
When I implemented `scan` on `Observable` I copied the behavior of Rx.NET, which as I remember does not emit the first element, see for example the [introtorx article](http://www.introtorx.com/Content/v1.0.10621.0/07_Aggregation.html#Scan).

For `Observable` it makes sense to skip the first element because consistency with ReactiveX is important and the implementation gets more complicated otherwise, plus you can always prepend it if you really need it. 

I'm more worried about the type-classes in Cats and about [scanl in Haskell](https://hackage.haskell.org/package/base-4.10.1.0/docs/Prelude.html#v:scanl). So Haskell has an overload called `scanl1` that skips the first item.

For now I'd rather leave it like it is, with explicit documentation in the ScalaDoc.

**Comment by oleg-py** [comment]
> consistency with ReactiveX

I looked into implementations for different languages, and it seems that [RxJava](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#scan-R-io.reactivex.functions.BiFunction-) and [RxScala](http://reactivex.io/rxscala/scaladoc/index.html#rx.lang.scala.Observable) (and RxKotlin/RxClojure, being wrappers around RxJava) actually emit the initial item, while implementations for other languages don't. So the JVM-land consensus seems to be different.

> plus you can always prepend it if you really need it.

You can always do `.drop(1)` as well.

That, and I find emitting the seed of `scan` useful when modelling the state of UI in application, i.e. this is my primary use case:
```scala
val allEvents = ???
val allStates = allEvents.scan(initialState)(handleEvent)
```
and I have been bitten by this resulting in a stream that never emits `initialState`.

> I'm more worried about the type-classes in Cats

Currently there's no typeclass that specifies `scan` operation (although it [can be](https://stackoverflow.com/a/47914820/2758343) implemented using existing ones). I couldn't find one for Haskell as well.

> For now I'd rather leave it like it is

Sure. I just wanted to raise a question before first release of `3.x`, since it's a breaking change.

**Comment by alexandru** [comment]
> I looked into implementations for different languages, and it seems that RxJava and RxScala actually emit the initial item

Really? This is kind of a problem. RxJava has diverged from Rx.NET so I'm not surprised.

Thanks for being thorough.

Leaving this open for investigation of implementation complexity, plus we need at least a ScalaDoc change.
