### ISSUE TITLE
Async Tasks Submitted to Full Run Queues are Orphaned

### ISSUE THREAD

**Issue by pettyjamesm** [monix/monix#594]
Just hit this today and can submit more details later, but thought I'd submit the issue anyway in case the fix is easy on my side. Tasks that asyncBoundary and executeOn (eg: IO schedulers) stop executing entirely if the IO scheduler throws a rejected execution exception.

**Comment by pettyjamesm** [comment]
I should say, in our case this is a database IO pool, thread-sized against the connection pool size, and where we actually want the rejected execution behavior to prevent unbounded growth of the thread pool beyond a certain queue limit. This is especially painful during auto scaling where fresh instances have yet to hit the server side prepared statement threshold and are still warming up the JIT, but are coming online under situations of heavy load.

**Comment by alexandru** [comment]
@pettyjamesm sorry for the delay in response.

It's pretty bad if the execution context throws an error and the task will probably become non-terminating, because it's currently a protocol violation — consider that the callback given in `Task.create` needs to be called at most once, so once you pass that callback to another piece of logic, if any of that logic throws, then in absence of further synchronization (which is slow), all you can safely do is to log the error.

I'm not a fan of using errors like that for limiting growth. It's better if you have some back-pressure mechanism.

But please describe the wanted behavior. I'm guessing that you want the task to end in error. I guess that if there's a specific error that the thread pool throws, we could recognize it and treat it as a case where we can signal the error via the callback.

So if the solution is straightforward, I'm willing to accept a PR.

**Comment by alexandru** [comment]
Note that we might be able to treat just `Task.shift` / `Task.delay*` / `Task#executeAsync` and leave `Task.create` alone — because there it's the user's responsibility to catch and treat errors.

**Comment by pettyjamesm** [comment]
Closing issue as likely resolved by https://github.com/monix/monix/pull/666 . As mentioned in that PR, our code base already works around the issue by using Task.create directly, but the test suite seems reasonable to guarantee the implementation handles this case now. Thanks for the great open source project.
