### ISSUE TITLE
TaskLocal should take Local

### ISSUE THREAD

**Issue by pettyjamesm** [monix/monix#595]
Under the hood, a TaskLocal creates a Local instance to pass context around, which is great- because hopefully the average use case is wrapped inside of a Task anyway so TaskLocal is a sane API on top of an unsafe mutable one. Unfortunately my use case is to trace operations in APIs that are inherently synchronous (JDBC) and it would be nice if TaskLocal could share an existing Local so that tracing use cases don't have to do gymnastics to synchronize state between the two.

**Comment by oleg-py** [comment]
@pettyjamesm why not use `Local` directly instead of `TaskLocal`, if you need it?

**Comment by pettyjamesm** [comment]
@oleg-py that's probably my workaround if this proposed change isn't made. Ideally I want to use the TaskLocal API to manipulate context wherever possible. However, in a couple places there really is no option to wrap the current operation in a Task and the ability to use the underlying Local directly would solve that problem for me. Without being able to back a TaskLocal with a given Local, I'm stuck either using Local everywhere or trying to keep a TaskLocal in sync with some other thread local state.

It feels like it would be easier to (optionally) pass the Local to TaskLocal to get the best of both worlds.

**Comment by Avasil** [comment]
It looks like easy change, similar to `KafkaConsumer` in `monix-kafka` but I didn't play with `TaskLocal` enough to reason about implications. What do you think @leandrob13 ?

**Comment by oleg-py** [comment]
I think it goes against design goals of `eval` subproject, as stated in #539. However, I don't see why it can't go other way around and ~~reflect~~ get `Task[Local[A]]` from `TaskLocal[A]`. So that as long as you're in `Task` context, you can extract the thing out and pass it downstream. I think @alexandru should give the casting vote.

**Comment by alexandru** [comment]
> get `Task[Local[A]]` from `TaskLocal[A]`

I can agree to that, however note that when combining usage of `Local` with `TaskLocal`, the usage patterns aren't necessarily compatible.

See what @leakyabstraction wrote here: https://gist.github.com/leandrob13/382df8a7b8cec321bf5d2791df240889

If that's acceptable, then OK, but you need to be aware that `TaskLocal.bind` will restore the original local value on the thread where the `Task`'s run-loop ends up.

So if you pass the `TaskLocal` to some computation, you might end up noticing that the `Local` has been modified on the current thread and isn't restored to its initial value. And that's because when working with `Task`, you basically forgo the notion of threads.

Example:

```scala
// Lets assume these 2 are linked:
val taskLocal: TaskLocal[Int] = ???
val local: Local[Int] = ???

val bound = taskLocal.bind(100) {
  someTask.flatMap(x => taskLocal.read.map(_ + x))
}

// Execution — at this point `local` gets modified to 100 and is 
// not necessarily restored, because restoration happens within the context 
bound.runAsync
```

So if you combine them like that, you're going to get this effect.

If you find that's acceptable, please submit a PR to expose a `def local: Task[Local[A]]` method on `TaskLocal`, as @oleg-py is suggesting.

**Comment by alexandru** [comment]
So, anybody for submitting a PR?

**Comment by Avasil** [comment]
@alexandru I guess I could do that, I wanted to dive deeper into `TaskLocal` anyway

**Comment by leandrob13** [comment]
@alexandru @Avasil  Sorry to be late for this discussion but I am wondering why a Task[Local] and not a Coeval[Local] if the use case is for sync operations and when there is no `Task` context needed?
