### ISSUE TITLE
Should (some?) operations on Iterant be lazy by default?

### ISSUE THREAD

**Issue by megri** [monix/monix#637]
As asked on gitter:
`val nats: Iterant[F] = Iterant[F].eval(1L) ++ nats.map(_ + 1)` fails with a stack overflow exception due to `++` strictly evaluating the rhs argument. Is this intentional? I find this way of expressing recursive lazy structures pretty convenient.

`Iterant.suspend(nats.map(_ + 1))` solves the strictness issue, just wondering if maybe this should be the default case for operations like concatenation.

**Comment by alexandru** [comment]
It's intentional.

Not sure if it's the best decision, but I'd rather have laziness managed by `F[_]` instead of by-name params, otherwise the default is strictness, following Cats's philosophy.

Btw, `++` has an overload, so you can also do ... `Iterant[F].eval(1L) ++ F.delay(nats.map(_ + 1))`

**Comment by oleg-py** [comment]
I'm with @megri  on this one.

For some operations on _concrete_ data types I think by-name parameters make more sense than by-value, e.g. `Option.getOrElse`. I think it's the same case with `Iterant.++`. IMO the `StackOverflowError` and possible strictness is totally not something a user of `Iterant` should need to be cautious about. I also myself have constructed lazy streams in fashions similar to above, and see this as totally valid.

Since we can take care of this for user on API level, I think we just should. Or is there some benefit to strict version besides saving on few allocations?

BTW, fs2 `++` takes by-name parameter as well.

**Comment by alexandru** [comment]
I have created 3 issues based on this:

- https://github.com/monix/monix/issues/644
- https://github.com/monix/monix/issues/643
- https://github.com/monix/monix/issues/642

Will now close this issue.
