### ISSUE TITLE
Add CancelableFuture.onCancelRaiseError

### ISSUE THREAD

**Issue by alexandru** [monix/monix#650]
`Task` currently has this method:

```scala
def onCancelRaiseError(e: Throwable): Task[A]
```

In Monix, on cancelation, tasks become normally non-terminating. But sometimes we don't want tasks that are non-terminating on cancelation, but rather we want tasks that terminate in error. And that's what this function does — turns tasks that are non-terminating on cancel, into ones that complete in error.

We need it for `CancelableFuture` as well:

```scala
sealed abstract class CancelableFuture[+A] extends Future[A] with Cancelable {
  // ...
  def onCancelRaiseError(e: Throwable): CancelableFuture[A]
}
```

**Comment by oleg-py** [comment]
So, I was looking into this and I have a question

```scala
val a: CancelableFuture[Int] = ???
val b: CancelableFuture[Int] = ???

val c = (a zip b).onCancelRaiseError(new Exception)
```

What should happen to `c` if either `a` or `b` is cancelled? I see two options:

- `c` becomes non-terminating. This is easiest to implement, but is likely to catch users by surprise
- `c` terminates in error. This requires changing quite a lot of `Cancelable` hierarchy so they can propagate cancellation to the top.

`Task` obviously doesn't have this problem due to laziness, but `Future` represent a computation that is already running, so this requires some kind of propagation from the bottom up.

**Comment by alexandru** [comment]
I don't think I want this for now.

The "continual" model is under revision. We can add it later.
