### ISSUE TITLE
Monix should make use of a HashWheelTimer for large timeout scheduling.

### ISSUE THREAD

**Issue by hepin1989** [monix/monix#658]
https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/HashedWheelTimer.java

https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala

https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/DeadlineTimerWheel.java

**Comment by hepin1989** [comment]
the minimal tick is 1ms on linux and 10ms on windows

**Comment by alexandru** [comment]
Sorry for not replying, I basically lost track of opened issues and now making an effort to get on top of things.

We're using the schedulers available in the standard Java library. But the Scheduler can be customized. You can easily implement your own to use whatever scheduling method you'd like.

Importing an implementation from somewhere else in Monix isn't feasible because we then have to maintain it.

Thanks for the suggestion. Will close this for now.
