### ISSUE TITLE
Circuit Breaking not doing a second attempt

### ISSUE THREAD

**Issue by MateuszKubuszok** [monix/monix#682]
I want to `TaskCircuitBreaker` to retry querying external service with an exponential backoff in case I used up quota. I wrote a utility class that does exactly that basing on [docs for Monix 3](https://monix.io/docs/3x/eval/circuit-breaker.html#usage):

```scala
import monix.eval._
import monix.execution._

import scala.concurrent._
import scala.concurrent.duration._

object ServiceRetry {

  private val circuitBreaker = TaskCircuitBreaker(
    maxFailures = 10,
    resetTimeout = 1.secod,
    exponentialBackoffFactor = 2.0,
    maxResetTimeout = 1.hour
  )

  def retryAction[T](thunk: => T)(implicit ec: ExecutionContext): Future[T] =
    retryTask(Task.eval{ println("try"); thunk }).runAsync(Scheduler(ec))

  def retryFuture[T](thunk: => Future[T])(
    implicit ec: ExecutionContext): Future[T] =
    retryTask(Task.deferFuture(thunk)).runAsync(Scheduler(ec))

  def retryTask[T](task: Task[T]): Task[T] =
    circuitBreaker.flatMap(_.protect(task))
}
```

However, when I wanted to test it, it failed. I rewrote the test to use only raw `Task` and `TaskCircuitBreaker`:

```scala
  "Task protected with TaskCircuitBreaker" must {
    "retry if an exception is thrown" in {
      var shouldFail = true
      whenReady(
        TaskCircuitBreaker(
          maxFailures = 1000,
          resetTimeout = 1.milli,
          exponentialBackoffFactor = 2.0,
          maxResetTimeout = 1.hour
        ).flatMap(_.protect(Task {
          if (shouldFail) {
            shouldFail = false
            throw new Exception("boom!")
          } else {
            123
          }
        })).runAsync
      ) { _ mustBe 123 }
    }
  }
```
which fails with
```
The future returned an exception of type: java.lang.Exception, with message: boom!.
```
If I put a `println` inside a Task's body I can see that it is only executed once.

I am wrong about how `TaskCircuitBreaker` should work? I use Monix 3 RC-1.

**Comment by alexandru** [comment]
Two observations:

1. in your test you're not retrying the task — the circuit breaker does not retry the task for you
2. doing `circuitBreaker.flatMap(_.protect(task))` will not work, because it's creating a new `TaskCircuitBreaker` instance on each call and that's not what you want

Usually `TaskCircuitBreaker` needs to be carried around as a parameter. If you can't do that for some reason, you can use `memoize` on that `Task`, but that can break referential transparency — not necessarily a bad thing if you can reason about it, but it's a good idea to have a good grasp of what "referential transparency" means.

**Comment by MateuszKubuszok** [comment]
Thanks for answer! It was not clear to me that I need to retry myself. I am using it in context where referential transparency would not be possible anyway (calling external services that change returned results over time).
