### ISSUE TITLE
Add ability to configure ConcurrentQueue.unbound() per operation

### ISSUE THREAD

**Issue by YulawOne** [monix/monix#701]
Could we consider for Monix 3.0 add ability to configure underlying unbound queues buffer not only globally but also per operation? 

The problem which I'm trying to solve with that is excessive memory consumption by WS streams in our application, due to a few merge operations with back pressure strategy, each merge stage creates queue with 1024 elements buffer under the hood which consumes ~4kb (~8kb in total for two operations) being at that moment just empty. While it could be seen negligible, however when application has 30K WS it already consumes ~240mb (in total for two operations). 

Due to lack of ability to configure buffer per operation we have to set size globally, and this puts restriction on whole application. For me it seems inefficient because there could be other parts of application which may require bigger size of the buffer.

**Comment by oleg-py** [comment]
Changing it per operation would probably mean having an extra (implicit) parameter added to each method. If so, it wouldn't play nicely with cold observables, and so is unlikely to be done.

**Comment by YulawOne** [comment]
I think we can achieve this for `AbstractBackPressuredBufferedSubscriber` without additional parameters if use `math.min(bufferSize, Platform.recommendedBatchSize)` for underlying `ConcurrentQueue.unbounded()` instance. And for me it seems quite logically, why do we need queue with chunks larger than outer buffer?

**Comment by alexandru** [comment]
I don't understand the request.

What do you mean "per operation"? In the case of `ConcurrentQueue`, this exposes the buffer — the buffer is the queue, the queue is the buffer so to speak. In case you've got multiple operations with different requirements, you can configure multiple queues.

In the case of `unbounded`, indeed the underlying implementation uses a "chunked array queue", so it grows in chunks. Is the problem that the chunks are too big? You can configure it to use smaller chunks.

---

If the problem is that you need to publish the same events to multiple consumers, then we are talking about a way to manage multiple queues (meant for different purposes) but that get the same signals (e.g. a broadcast setup).

I am working on a `ConcurrentChannel` that addresses this use-case. The interface is like this:

```scala
class ConcurrentChannel[F[_], E, A](implicit F: Async[F], timer: Timer[F]) {

  def push(a: A): F[Boolean]

  def pushMany(seq: Iterable[A]): F[Boolean]

  def pushMany(seq: Iterable[A]): F[Boolean]

  def consume(
    capacity: BufferCapacity, 
    channelType: ChannelType): Resource[F, ConsumerF[F, E, A]]

}
```

Where `ConsumerF` is this:

```scala
trait ConsumerF[F[_], E, A] {

  def pull: F[Either[E, A]]

  def pullMany(maxLength: Int): F[Either[E, Seq[A]]]
}
```

So whenever you use `consume`, you create a new internal queue that gets added to the set of queues that incoming messages need to be published on — thus you can have unicast, broadcast, or multicast setups.  `ConcurrentChannel` is a way to push the same messages to multiple consumers, working essentially like a `PublishSubject` and where each subscriber gets its own buffer.

This however will get published post 3.0.0, because I can't delay the release and I need to get it right.

**Comment by YulawOne** [comment]
Sorry that my previous statement became so ambiguous, I just wanted to describe following situation:

Let's pretend that we have two or more sources of events per client and we want to send all of them all into one web socket channel, all sources are back pressured, so my implementation is something like this:

```scala

trait ClientEvents {
  type ClientId

  trait Event

  def sourceOfEvents1(clientId: ClientId): Observable[Event]

  def sourceOfEvents2(clientId: ClientId): Observable[Event]

  def allEvents(clientId: ClientId): Observable[Event] =
    Observable(sourceOfEvents1(clientId), sourceOfEvents2(clientId)).merge()
}

```

And merge operation is source of the issue which i'm trying to describe, because `MergeMapObservable` `(monix.reactive.Observable#mergeMap (monix/reactive/Observable.scala:2222))` 

creates instance of BufferedSubscriber inside `(monix/reactive/internal/operators/MergeMapObservable.scala:43)`

And as default strategy was selected, the BackPressure OverflowStrategy will be used `(monix/reactive/observers/buffers/BuildersImpl.scala:32)`

That all means that `BackPressuredBufferedSubscriber` will be used, and if we go inside of implementation we will see there `ConcurrentQueue.unbounded()` instance `(monix/reactive/observers/buffers/AbstractBackPressuredBufferedSubscriber.scala:45)`

Which as you can see has buffer size defined as platform wide and it's not possible to configure it per operation, which means each merge operation will cost at least ~4kb (size of single empty chunk) and the only possible way to decrease memory consumption is changing global configuration. 

For regular application it's ok but when you have several dozen thousands of active websockets it became an issue with severe memory consumption on one side and sub-optimal global configuration for buffer on other. 

Your suggestion with `ConcurrentChannel` is a possible way to solve that issue, but I think it creates complexity where it's not necessary and simpler solution would be to provide way to pass size of buffer from declaration of merge operation. My previous suggestion was to use parameter `bufferSize` of `BackPressure` strategy as parameter for unbound queue there.

Anyway thank you for spending your time into that issue.

**Comment by alexandru** [comment]
@YulawOne so what I understand is that the buffer created for `OverflowStrategy.BackPressure` is an unbounded queue that has a chunk size of `Platform.recommendedBatchSize` and this is a problem because it uses too much memory per merge operation. Is that correct?

I'm not sure how to solve this, because that chunk size is an implementation detail of the underlying queue being used. I mean in other situations the whole buffer size is being allocated, not just in chunks.

I guess we can add a `chunkSizeHint` to `OverflowStrategy`. And/or reconfigure that default to be lower.

What do you think a good solution would be?

We need to hurry with this though, because I wanted to release 3.0.0 and this smells like a breaking change.

**Comment by alexandru** [comment]
You do seem to have a serious use of `merge` in your app that I want to support 🙂

**Comment by YulawOne** [comment]
> @YulawOne so what I understand is that the buffer created for OverflowStrategy.BackPressure is an unbounded queue that has a chunk size of Platform.recommendedBatchSize and this is a problem because it uses too much memory per merge operation. Is that correct?

Correct

> I'm not sure how to solve this, because that chunk size is an implementation detail of the underlying queue being used. I mean in other situations the whole buffer size is being allocated, not just in chunks.
> I guess we can add a chunkSizeHint to OverflowStrategy. And/or reconfigure that default to be lower.
> What do you think a good solution would be?

My suggestion was to use outer buffer size as chunk size, so you'd be able to configure underlying queue with BackPressure  Strategy buffer size:

```scala
def unbounded[A](size: Int = Platform.recommendedBatchSize): ConcurrentQueue[A] = {
  if (UnsafeAccess.IS_OPENJDK_COMPATIBLE) {    
    new FromMessagePassingQueue[A](new MpscUnboundedArrayQueue[A](size))
  }
  else {
    val ref = new MpscLinkedAtomicQueue[A]()
    new FromAbstractQueue[A](ref)
  }
}
```

And inside AbstractBackPressuredBufferedSubscriber set queue size equal to bufferSize
```
  protected final val queue: ConcurrentQueue[A] =
    ConcurrentQueue.unbounded(_bufferSize)
```

There is pros and cons for such change 
pros:
 - this change won't make any changes to existing api and could altered in future
 - for me it seems logical to have same size buffer and chunk, but to be sure there should be some benchmark which show relations between outer buffer and queue

cons:
 - we introducing relation between things that are not relative
 - from performance perspective is uncertain change

> You do seem to have a serious use of merge in your app that I want to support 

Let me make slight insight into my domain and what use case of monix I have - I'm developing customer support system with embedded chat in to it. Both support agents and customers receive updates via WS, currently it's about 10k-15k average and up-to 30k simultaneous WS connections during spikes. Nodes on backend scales with Akka Cluster with extensive usage of Akka Cluster PubSub. Most of things that are done with monix is merging and routing various event source for customer/support agent. In average we have 3 merge stages per connection and with default `Platform.recommendedBatchSize` we start getting OOM due severe memory consumption

**Comment by alexandru** [comment]
@YulawOne you are right that at the very least the chunk size shouldn't be greater than the declared buffer size.

Let me sleep on it, but will deliver a solution for the next release.

**Comment by alexandru** [comment]
@YulawOne as an update, I'm working on this, see: https://github.com/monix/monix/pull/801

**Comment by YulawOne** [comment]
@alexandru thank you for great job, I will definitely check PR on this week.
