### ISSUE TITLE
Observable.resourceCase don't fit well with mergeMap

### ISSUE THREAD

**Issue by crakjie** [monix/monix#764]
`Observable.resourceCase` close the resource while `mergeMap` is still using it. 
`flatMap` is working well in this case.

**Comment by alexandru** [comment]
Thanks for the report @crakjie, will take a look.

Indeed, the correct behavior is that of `flatMap` and `resourceCase` was designed to play well with `flatMap`. 

On the other hand `mergeMap` should work too.

Can you provide a minimal sample? Or does it happen with anything?

**Comment by alexandru** [comment]
I just realized that `resourceCase` cannot work with `mergeMap` or any operator that involves buffering.

```scala
Observable.resourceCase(acquire)(release).flatMap { resource =>
  resource.use
}
```

This only works because it relies on back-pressuring. With no back-pressuring, the resource gets closed early. E.g. this no longer works ..

```scala
Observable.resourceCase(acquire)(release)
  .asyncBoundary(Unbounded)
  .flatMap { resource =>
    resource.use
  }
```

By introducing a buffered async boundary in there, we eliminate the back-pressuring of the source and hence this sample breaks.

`mergeMap` breaks because `mergeMap` implies a concurrent buffer because it is a concurrent operator and thus it eliminates the back-pressuring (actually it still back-pressures, because the buffer is limited, but it doesn't back-pressure for our purposes here).

`Observable.resourceCase` is made to work with `flatMap`. In other words, don't use `mergeMap` when you mean `flatMap`.

**Comment by crakjie** [comment]
Seems logic I don't know why I missed this.
Thanks

**Comment by alexandru** [comment]
@crakjie it's not very obvious sometimes and it's a more general problem with the "bracket" model, as resources can leak after close. Fixing it however would require language support that we don't have.
