### ISSUE TITLE
Cancel not being called

### ISSUE THREAD

**Issue by Ben-Barron** [monix/monix#776]
I would expect (admittedly based on experience with RX in Java and .NET) that `.cancel()` would be called in this scenario:

(Please forgive my syntax if its wrong)

```
Observable.create[String](Unbounded) (
  o -> {
    o.onNext("value")
    Cancelable(() => println("cancel"))
  }
).take(1).subscribe()
```

I actually found the same problem when: `Await.result(observable.firstL.runAsync, 4.seconds)`, but it would appear the above still has issues to.

Am I wrong to expect `.cancel()` to be called? And if so, what is the recommended way of cleaning up resources on termination of the stream?

Monix v2.3.2
Scala 2.12.6

**Comment by alexandru** [comment]
@Ben-Barron in Monix's `Observable` cancellation is a concurrent action that gets triggered in order to interrupt the streaming (the subscription) and not something that happens on normal completion.

The [contract of Observer](https://monix.io/docs/3x/reactive/observers.html) specifies that `onNext` is something that returns a `Future[Ack]`, which can be a `Stop` and you need to listen to that, because the subscriber has the possibility of issuing `Stop` events for a more cooperative interruption that doesn't need to be concerned with concurrency issues.

Actually if you can switch to `3.0.0-RC2`, which is fairly stable, you can work with:

- [resource](https://monix.io/api/3.0/monix/reactive/Observable$.html#resource[A](acquire:monix.eval.Task[A])(release:A=%3Emonix.eval.Task[Unit]):monix.reactive.Observable[A]) (the builder)
- [guarantee](https://monix.io/api/3.0/monix/reactive/Observable.html#guarantee(f:monix.eval.Task[Unit]):monix.reactive.Observable[A]) (the method)

I'm mentioning `3.0.0-RC2` because `resource` or `guarantee` are the way to go. I've recently published a tutorial here: https://monix.io/blog/2018/11/07/tutorial-bracket.html

If you're stuck with `2.3.2` for now, you can use this combination:

- [doOnTerminate](https://monix.io/api/2.3/monix/reactive/Observable.html#doOnTerminate(cb:Option[Throwable]=%3EUnit):Self[A]) (or `doOnTerminateEval`)
- [doOnSubscriptionCancel](https://monix.io/api/2.3/monix/reactive/Observable.html#doOnSubscriptionCancel(cb:()=%3EUnit):Self[A]) (which basically does what you did above)

It's not ideal, but the two ways of interrupting a stream are distinct enough that during 2.x I felt a strict separation was needed.

**Comment by Ben-Barron** [comment]
Unfortunately stuck with 2.3.2 for now. If I've understood you correctly, to cleanup the resources under all scenarios I need to do (something like) the following:

Observable.defer[String]({
  var cancelable = null
  Observable.create[String](Unbounded)({
    o => {
      o.onNext("hey")
      cancelable = Cancelable(() => println("cancel"))
      cancelable
    }
  })
  .doOnSubscriptionCancel(() => cancelable.cancel())
  .doOnTerminate(_ => cancelable.cancel())
})

Is that correct?

**Comment by alexandru** [comment]
@Ben-Barron first of all you don't need to use a `var`, because there's `SingleAssignCancelable` meant for this purpose. It's also best to avoid `create`.

But lets walk through a full example:

```scala
def linesFromFile(file: File): Observable[String] =
  Observable.defer {
    val in = new BufferedReader(new InputStreamReader(new FileInputStream(file), "utf-8"))
    val token = Cancelable(() => in.close())

    Observable.repeatEval(in.readLine())
      .takeWhile(_ != null)
      .doOnSubscriptionCancel(() => token.cancel())
      .doOnTerminate(_ => token.cancel())      
  }
```

Expressing this in terms of `create` would be like:

```scala
def linesFromFile(file: File): Observable[String] =
  Observable.create { out =>
    val token = SingleAssignCancelable()
    // Forking a logical thread
    out.scheduler.executeAsync { () =>
      try {
        val in = new BufferedReader(new InputStreamReader(new FileInputStream(file), "utf-8"))    
        token := Cancelable(() => in.close())
        var wasStopped = false
        var continue = true

        while (continue) {
          val line = in.readLine()
          if (line != null)
            out.onNext(line) match {
              case Stop => 
                // Interrupting, as a deterministic request from downstream
                wasStopped = true
                token.cancel()
              case Continue =>
                () // continue
            }
          else {
            continue = false
          }
        }
        if (!wasStopped) {
          token.cancel()
          out.onComplete()
        }
      } catch {
        case NonFatal(e) =>
          out.onError(e)
      }
    }
    // Returning cancellation token
    token
  }
```

One thing to consider: the first version is actually better than the second version, because `Observable.create` creates a buffer to relieve you from dealing with back-pressure concerns.  The first version doesn't do that.

To recreate the first version by going low level, you'd have to use `unsafeCreate` and take care of back-pressure concerns, as described in the article I gave you:

```scala
def linesFromFile(file: File): Observable[String] = {
  def loop(in: BufferedReader, out: Subscriber[String], token: Cancelable): Future[Ack] = {
    implicit val ec = out.scheduler
    try {
      val line = in.readLine()
      if (line != null)
        // N.B. syncFlatMap is an extension method provided by Monix, an optimization
        // over flatMap to be just trampolined
        out.onNext(line).syncFlatMap {
          case Continue => 
            // recursive call, continue, do next line
            loop(in, out, token) 
          case Stop =>
            token.cancel()
        }
      else {
        token.cancel()
        out.onComplete()
      }
    } catch {
      case NonFatal(e) =>
        out.onError(e)
    }
  }

  Observable.unsafeCreate { out =>
    val token = SingleAssignCancelable()
    // Forking a logical thread
    out.scheduler.executeAsync { () =>
      try {
        val in = new BufferedReader(new InputStreamReader(new FileInputStream(file), "utf-8"))    
        token := Cancelable(() => in.close())
        loop(in, out, token)
      } catch {
        case NonFatal(e) =>
          out.onError(e)
      }
    }
    // Returning cancellation token
    token
  }
}
```

This is the low level protocol so to speak. You're better off working with the high level operators though.  As can be seen in the first example, it's more readable and does the right thing out of the box.

Use `create` or `unsafeCreate` when you need to do imperative pushes (e.g. when you have a data source whose rate you cannot control).

**Comment by alexandru** [comment]
Will close this for now, but feel free to add more comments.
