### ISSUE TITLE
"Iterant.resource does not require non-strict use" hangs Travis CI

### ISSUE THREAD

**Issue by Avasil** [monix/monix#809]
[Iterant.resource does not require non-strict use](https://github.com/monix/monix/blob/master/monix-tail/shared/src/test/scala/monix/tail/IterantResourceSuite.scala#L264) has been a problem for Travis for a while. It just hangs and fails the build. I didn't manage to find out why but it only happens with coverage enabled. 

If we don't know how to fix it we could try disabling this test for coverage run. It's possible with `ScalaTest` Tags but `monix-tail` uses `minitest`

**Comment by alexandru** [comment]
We have another problem due to the way Minitest works ... I couldn't make it flush the output on each line, for some reason `sbt-testing` insists on flushing the whole output only when the test suite is finished. And I've been too lazy to fix it.

In other words, are you sure it is that particular test that fails?

**Comment by Avasil** [comment]
> In other words, are you sure it is that particular test that fails?

Yeah:

https://travis-ci.org/monix/monix/jobs/476745541

https://travis-ci.org/monix/monix/jobs/469978844

https://travis-ci.org/monix/monix/jobs/458096430

https://travis-ci.org/monix/monix/jobs/468917467

https://travis-ci.org/monix/monix/jobs/467941117

https://travis-ci.org/monix/monix/jobs/467941071

https://travis-ci.org/monix/monix/jobs/466223385

https://travis-ci.org/monix/monix/jobs/458674896

It's always the same test and it can pass after few tries

**Comment by alexandru** [comment]
So the output of these tests is misleading for precisely the reason I was talking about.

After we get to the bottom of it and find the failing test (in #812), I'm thinking of getting rid of our code coverage reporting, because it's mostly useless and adds tremendous overhead to the Travis build.

We're talking of a 30 minutes overhead, so the build with coverage on takes 43 minutes, versus 13 minutes without it. And that's not acceptable.

**Comment by Avasil** [comment]
+1 on disabling it, we can always run it locally if we're wondering about our test cases

**Comment by alexandru** [comment]
I've disabled it. I'm seeing all builds green for now 🙂

Unfortunately in #812 I did not get a build failure to be able to investigate.
