### ISSUE TITLE
Local is exposing too many implementation details

### ISSUE THREAD

**Issue by alexandru** [monix/monix#923]
We should make the `Context` class in `Local` private or at least its implementation.

Is there any reason for the user to have access to the methods of `Context` or to `Bound` / `Unbound`?

The problem is that I'm sure this isn't the final `Local` implementation and it would be a pity to break binary compatibility for simple fixes.

**Comment by alexandru** [comment]
> Is there any reason for the user to have access to the methods of Context or to Bound / Unbound?

Actually I see that the macros are calling those methods now 🙂 I'm a little worried that we are exposing methods with `Any` in their signature.

Also are the `Bound` / `Unbound` classes required to be public?

**Comment by oleg-py** [comment]
Pretty sure Bound / Unbound being public is an oversight.

We could remove macros for other cases, if they aren't really buying us much performance. I preserved them as they were already here.

Also we can make things `private[monix]` (should be bincompatible, IIRC that translates to JVM public anyway). I had some ideas for a Local that can work for any F if its ContextShift is backed by a `TracingScheduler`, which is why I left things quite lax.

At least parts that are used in `TaskLocal` should remain public for anybody daring to do such thing. One thing in particular is that `isolate` needs to be reimplemented in terms of effect type's `bracket` with `getContext`/`setContext`.

**Comment by Avasil** [comment]
Fixed in #946, I assume we don't do anything else related to it
