### ISSUE TITLE
Coeval.*> and <* combinator

### ISSUE THREAD

**Issue by Avasil** [monix/monix#930]
It can be found in [cats.Apply](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Apply.scala) syntax and/or [cats.FlatMap](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/flatMap.scala)

but it's very common to use, so importing cats all the time is annoying.

```scala
final def *>[B](that: => Coeval[B]): Coeval[B]
final def <*[B](that: => Coeval[B]): Coeval[A]
```

```scala
coevalA *> coevalB // runs coevalA , then coevalB, returns the result of coevalB
coevalA <* coevalB // runs coevalA , then coevalB, returns the result of coevalA
```

**Comment by valenterry** [comment]
I can pick it up

**Comment by alexandru** [comment]
Hey, see my comments on #935.

`*>` and `<*` have a strict parameter in Cats and we need to be consistent with it.  We might also want to introduce `<<` and `>>` which have the non-strict parameter.

Also an `@inline` wouldn't hurt, I see that Cats uses the `@inline` annotation a lot for aliases, although I don't necessarily trust it.

And personally I'd prefer a PR for both Task and Coeval. We need too ensure consistency or otherwise we risk introducing an operator in Coeval that's missing in Task 🙂

**Comment by alexandru** [comment]
Well, the requirement for the single PR really is optional. If you're in the context of a hackathon, then I guess two PRs are preferable.

**Comment by valenterry** [comment]
> Well, the requirement for the single PR really is optional. If you're in the context of a hackathon, then I guess two PRs are preferable.

I am, but I can also merge the PRs - no problem
