### ISSUE TITLE
A typo of `Task[A]` in the document

### ISSUE THREAD

**Issue by CasterKKK** [monix/monix#979]
![image](https://user-images.githubusercontent.com/16066720/62834650-15431900-bc82-11e9-86f0-38e03a8e1ad8.png)

In https://monix.io/docs/3x/eval/task.html

Here, the type of `Task[A]` may be `() => (A => Unit) => Unit` rather than `(A => Unit) => Unit`?

**Comment by dylemma** [comment]
I don't think so.

The `(A => Unit)` part is the "callback" that can be called when the task has produced a value, and is part of the signature of the various `run` methods.

A signature like `() => (A => Unit) => Unit` would lead to client code like `task.run()(handleValue)`... the first `()` is unnecessary.

**Comment by alexandru** [comment]
You can view `Task` as being equivalent to `() => (A => Unit) => Unit`, this being basically Task's `runToFuture`.

But the regular `runAsync` is no different in its signature than Future's `onComplete`, being `(A => Unit) => Unit`. I think the confusing factor here is `Future`, because `Future` is memoized (being essentially a var), serving as an indirection, but you don't see that when looking at its signature.

Not sure how to describe this to make it correct, however in general in Scala, if you have strict behavior, to make it lazy you wrap it in a thunk, so if `A` is strict, then `() => A` will be non-strict and if `(A => Unit) => Unit` is strict, then `() => (A => Unit) => Unit` will be non-strict.

**Comment by alexandru** [comment]
In other words, this is a complicated problem and both of you are correct 🙂

**Comment by CasterKKK** [comment]
Got it. I just read the doc of Monix and Cats Effect, found the difference between these two tables and I was confusing about it. Learned a lot!
